FROM python:3.13-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y gcc libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем poetry
RUN pip install --no-cache-dir "poetry==2.1.4"

# Копируем файлы зависимостей
COPY pyproject.toml poetry.lock ./

# Устанавливаем зависимости
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-root --without dev,exec

# Копируем весь проект
COPY . .

# Запускаем приложение
# CMD ["gunicorn", "project_name.wsgi:application", "--bind", "0.0.0.0:8000"]